version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.15.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - super_network

  kibana:
    image: kibana:8.15.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - super_network

  logstash:
    image: logstash:8.15.4
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - super_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - super_network

networks:
  super_network:
    driver: bridge