spring:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


springdoc:
  api-docs:
    path: /api-docs

authentication:
  expiration: 10m
  remember-me-expiration: 30d
  secret: c2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OQBASDASFavsafasfasvbascascasvas