spring:
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gbhfns
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs