name: Fintech - github CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Calculate test coverage
        run: ./gradlew jacocoTestReport

      - name: Run static code analysis
        run: ./gradlew check

      - name: Build Docker image
        run: |
          docker build -t fintech-app:${{ github.sha }} .

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Packages
        run: |
          docker tag fintech-app:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/fintech-app:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/fintech-app:${{ github.sha }}